apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-color-git
  namespace: vnytech3-dev
  labels:
    app: simple-webapp-color-git
    app.kubernetes.io/component: simple-webapp-color-git
    app.kubernetes.io/instance: simple-webapp-color-git
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: simple-webapp-color-git-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  selector:
    app: simple-webapp-color-git
    deploymentconfig: simple-webapp-color-git
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer: {}
